keys:
  - &users:
    - &erwin age1jaur8fhv8xwzfdelc5mfjvtg52qk9v6v3rf93q49z9u8u9e86sls3jm9fn
  - &hosts:
    - &k3s-01 age19efl79ckwk9smaf56m36l0jy0s6hd769xxx6y6q6p0uqnvegve3qhmvcun
creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age:
          - *erwin
          - *k3s-01
